import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#005f6a",
        "primary-container": "#007a87",
        "primary-fixed": "#97f0ff",
        "primary-fixed-dim": "#7ad4e2",
        "on-primary": "#ffffff",
        "on-primary-container": "#d5f9ff",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f57",
        secondary: "#506164",
        "secondary-container": "#d3e6e9",
        "secondary-fixed": "#d3e6e9",
        "secondary-fixed-dim": "#b8cacd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#56676a",
        "on-secondary-fixed": "#0d1e21",
        "on-secondary-fixed-variant": "#394a4c",
        tertiary: "#824715",
        "tertiary-container": "#9f5f2b",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb782",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff0e7",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#6f3805",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006874",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3e494a",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        outline: "#6e797b",
        "outline-variant": "#bdc8cb",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#7ad4e2",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      boxShadow: {
        editorial: "0px 12px 32px rgba(25, 28, 29, 0.05)",
        card: "0px 4px 12px rgba(25, 28, 29, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
